//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropboxWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DropboxWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxWrapper.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression app folder path.
        /// </summary>
        internal static string CompressionAppText {
            get {
                return ResourceManager.GetString("CompressionAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DBW_icon {
            get {
                object obj = ResourceManager.GetObject("DBW_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxFolderPath.
        /// </summary>
        internal static string DropboxFolderPath {
            get {
                return ResourceManager.GetString("DropboxFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstRun.
        /// </summary>
        internal static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing path.
        /// </summary>
        internal static string MissingPath {
            get {
                return ResourceManager.GetString("MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\DropboxWrapper.
        /// </summary>
        internal static string RegistryPath {
            get {
                return ResourceManager.GetString("RegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run.
        /// </summary>
        internal static string RegistryStartupPath {
            get {
                return ResourceManager.GetString("RegistryStartupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadType.
        /// </summary>
        internal static string UploadType {
            get {
                return ResourceManager.GetString("UploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadTypeIndex.
        /// </summary>
        internal static string UploadTypeIndex {
            get {
                return ResourceManager.GetString("UploadTypeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrapFolderPath.
        /// </summary>
        internal static string WrapFolderPath {
            get {
                return ResourceManager.GetString("WrapFolderPath", resourceCulture);
            }
        }
    }
}
